name: Workflow Dispatch
description: Uses workflow dispatch to trigger a workflow in another repository
author: DrizlyInc/DVX

inputs:

  app_id:
    required: true
    description: App ID for a GitHub app with write permissions to the dispatching repository and target repository (for triggering workflows and writing creating checks)

  private_key:
    required: true
    description: Private key for the GitHub app id provided

  target_repository:
    required: true
    description: Name of the repository to target with the dispatch

  target_owner:
    required: true
    description: Owner of the target repository (user or organization)

  target_ref:
    required: false
    description: Ref which should be triggered on the target repository
    default: main

  workflow_filename:
    required: true
    description: The basename (no .yml extension) of the file in .github/workflows/ of the target_repository responding to the workflow_dispatch event

  wait_for_check:
    required: false
    default: false
    description: "Should the action wait for its check to finish? true | false"

  wait_timeout_seconds:
    required: false
    default: 120
    description: Number of seconds to wait for the check before timing out (ignored if wait_for_check is false). Inlcudes setup time to pull actions, etc

  workflow_inputs:
    required: true
    description: Inputs to pass to the workflow, must be a JSON encoded string ex. '{ "myinput":"myvalue" }'

runs:
  using: docker
  image: Dockerfile