name: PR Validation

on: pull_request

jobs:
  DistilleryX-terraform-plan:

    runs-on: ubuntu-latest
    steps:

      # - name: Checkout
      #   uses: actions/checkout@v2

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          tags: user/app:latest