name: PR Validation

on: pull_request

jobs:

  Validate:
    runs-on: ubuntu-latest
    steps:

      - name: Create Lowercase Image Name
        run: echo IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: build CI images
        run: |
          docker build --target builder -t ${{ env.IMAGE_NAME }}/builder . && \
          docker build --target unit-tester -t ${{ env.IMAGE_NAME }}/unit-tester . && \
          docker build --target linter -t ${{ env.IMAGE_NAME }}/linter .

      - name: Lint
        run: docker run --rm ${{ env.IMAGE_NAME }}/linter

      - name: Unit Test
        run: docker run --rm ${{ env.IMAGE_NAME }}/unit-tester

      # ---------------------------------------------

      - name: build production image
        run: |
          docker build \
            -t ${{ env.IMAGE_NAME}}:latest \
            -t ${{ env.IMAGE_NAME}}:${{ github.sha }} \
            .

      - name: Push To GitHub Container Registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ github.sha }} latest
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}