name: PR Validation

on: pull_request

jobs:

  Validate:
    runs-on: ubuntu-latest
    container: golang:1.16-alpine
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        run: gofmt -d -e .

      - name: Unit Test
        run: go test -v ./...

      # - name: Docker build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     tags: user/app:latest