name: PR Validation

on: pull_request

jobs:

  Validate:
    needs: Lint-And-Test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        run: docker-compose up linter

      - name: Unit Test
        run: docker-compose up unit-tester

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: user/app:latest