name: PR Validation

on: pull_request

jobs:

  Validate:
    runs-on: ubuntu-latest
    steps:

      - name: Prepare Image Name
        run: echo IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: build builder image
        run: docker build --target builder -t ${{ env.IMAGE_NAME }}/builder .

      - name: build unit-tester image
        run: docker build --target unit-tester -t ${{ env.IMAGE_NAME }}/unit-tester .

      - name: build linter image
        run: docker build --target linter -t ${{ env.IMAGE_NAME }}/linter .

      - name: Lint
        run: docker run --rm ${{ env.IMAGE_NAME }}/linter

      - name: Unit Test
        run: docker run --rm ${{ env.IMAGE_NAME }}/unit-tester

      - name: build production image
        run: docker build --target production -t ${{ env.IMAGE_NAME }} .

      # - name: Push To GitHub Container Registry
      #   uses: redhat-actions/push-to-registry@v2
      #   with:
      #     image: ${{ steps.build-image.outputs.image }}
      #     tags: ${{ steps.build-image.outputs.tags }}
      #     registry: quay.io/quay-user
      #     username: quay-user
      #     password: ${{ secrets.REGISTRY_PASSWORD }}