name: release

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  Say-Hello:
    runs-on: ubuntu-latest
    steps:

      - run: echo "Hello, World!"