name: Validate & Release

on: push

jobs:

  validate:
    runs-on: ubuntu-latest
    steps:

      - name: Create Lowercase Image Name
        run: echo IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: build CI images
        run: |
          docker build --target builder -t ${{ env.IMAGE_NAME }}/builder . && \
          docker build --target unit-tester -t ${{ env.IMAGE_NAME }}/unit-tester . && \
          docker build --target linter -t ${{ env.IMAGE_NAME }}/linter .

      - name: Lint
        run: docker run --rm ${{ env.IMAGE_NAME }}/linter

      - name: Unit Test
        run: docker run --rm ${{ env.IMAGE_NAME }}/unit-tester

  release:
    # if: ${{ github.ref == 'refs/heads/main' }}
    needs: validate
    runs-on: ubuntu-latest
    steps:

      - name: Parse Version From action.yml
        run: echo VERSION=$(cat action.yml | tail -1 | cut -d ':' -f4) >> $GITHUB_ENV

      - name: debug
        run: echo ${{ env.VERSION }}

      # - name: Build and Publish Image
      #   uses: matootie/github-docker@v3.1.0
      #   with:
      #     accessToken: ${{ secrets.GITHUB_TOKEN }}
      #     containerRegistry: true
      #     tag: |
      #       latest
      #       ${{ github.sha }}
